# Site settings
title: Pete Pixel
description: Pete's Resume
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:4000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Pete Pixel
user_description: Passionate about spreading the word of open source and digitalization
user_title: Open Source Advocate
email: pete.pixel∂emaildomain.com
linkedin_username: petepixel
github_username:  petepixel
expertise_picture: expertises.jpg

exclude: ['package.json', 'src', 'node_modules', 'vendor']

